config/routes.rb
Rails.application.routes.draw do
  resources :payments

  root 'home#index'
  resources :home
  resources :account_balances

  resources :accounts

  resources :order_payments

  resources :warehouses

  resources :product_histories

  devise_for :employees
  resources :godown_items

  resources :godown_entries do
    member do
      get :do_import
      get :import
      get :check
      get :clear_items
    end
  end

  resources :products

  resources :delivery_items

  resources :deliveries

  resources :partners

  resources :staffs

  resources :companies

  resources :order_items
  resources :product_warehouses

  resources :providers
  resources :employees do
    collection do
      post :add
    end
  end

  resources :orders do
    collection do
      get :prepare_import
      post :import
      get :autocomplete_godown_item_terminal_code
    end
    member do
      get :delivery
      post :add_item
      get :recaculate
      post :pay
    end
  end


end

app/models/staff.rb
class Staff < ActiveRecord::Base
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:name, :tel, :email, :position, :qq, :company_id)
    end
end

app/views/staffs/_form.html.haml
= simple_form_for(@staff) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :tel
    = f.input :email
    = f.input :position
    = f.input :qq
    = f.input :company_id

  .form-actions
    = f.button :submit

app/views/staffs/edit.html.haml
%h1 Editing staff

= render 'form'

= link_to 'Show', @staff
\|
= link_to 'Back', staffs_path

app/views/staffs/index.html.haml
%h1 Listing staffs

%table
  %tr
    %th Name
    %th Tel
    %th Email
    %th Position
    %th Qq
    %th Company
    %th
    %th
    %th

  - @staffs.each do |staff|
    %tr
      %td= staff.name
      %td= staff.tel
      %td= staff.email
      %td= staff.position
      %td= staff.qq
      %td= staff.company_id
      %td= link_to 'Show', staff
      %td= link_to 'Edit', edit_staff_path(staff)
      %td= link_to 'Destroy', staff, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Staff', new_staff_path

app/views/staffs/new.html.haml
%h1 New staff

= render 'form'

= link_to 'Back', staffs_path

app/views/staffs/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @staff.name
%p
  %b Tel:
  = @staff.tel
%p
  %b Email:
  = @staff.email
%p
  %b Position:
  = @staff.position
%p
  %b Qq:
  = @staff.qq
%p
  %b Company:
  = @staff.company_id

= link_to 'Edit', edit_staff_path(@staff)
\|
= link_to 'Back', staffs_path