config/routes.rb
Rails.application.routes.draw do
  resources :payments

  root 'home#index'
  resources :home
  resources :account_balances

  resources :accounts

  resources :order_payments

  resources :warehouses

  resources :product_histories

  devise_for :employees
  resources :godown_items

  resources :godown_entries do
    member do
      get :do_import
      get :import
      get :check
      get :clear_items
    end
  end

  resources :products

  resources :delivery_items

  resources :deliveries

  resources :partners

  resources :staffs

  resources :companies

  resources :order_items
  resources :product_warehouses

  resources :providers
  resources :employees do
    collection do
      post :add
    end
  end

  resources :orders do
    collection do
      get :prepare_import
      post :import
      get :autocomplete_godown_item_terminal_code
    end
    member do
      get :delivery
      post :add_item
      get :recaculate
      post :pay
    end
  end


end

app/models/employee.rb
class Employee < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def admin?
    self.roles && self.roles.include?('admin')
  end
  def to_s
    self.display_name
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ResourcesController
  def add
    #binding.pry
    params.permit!
    @object = Employee.new(params[:employee])
    if @object.save
      redirect_to employees_path
      return
    else
      @no_log = 1
    end
    render :new
  end
  private
    def employee_params
      params.require(:employee).permit(:email, :display_name, :password, :password_confirmation)
    end

end

app/views/employees/edit.html.haml
= simple_form_for(@object) do |f|
  = f.error_notification

  .form-inputs
    = f.input :email
    = f.input :display_name
    = f.input :roles

  .form-actions
    = f.button :submit

app/views/employees/index.html.haml
.toolbox
  = toolbox_button '新增员工', new_employee_path

%table.table.table-bordered.table-striped.table-hover
  %tr
    %th Email
    %th 名字
    %th 权限
    %th

  - @collection.each do |emp|
    %tr
      %td= emp.email
      %td= emp.display_name
      %td= emp.roles
      %td
        = link_to '详情', emp
        |
        = link_to '修改', edit_employee_path(emp)
        |
        = link_to '删除', emp, :method => :delete, :data => { :confirm => '你确认删除吗？' }

app/views/employees/new.html.haml
= simple_form_for(@object, url: add_employees_path) do |f|
  = f.error_notification

  .form-inputs
    = f.input :email
    = f.input :display_name
    = f.input :password
    = f.input :password_confirmation

  .form-actions
    = f.button :submit

app/views/employees/show.html.haml
.toolbox
  = toolbox_button '修改', edit_employee_path(@object)
  = toolbox_button '列表', employees_path
%p
  Email: 
  = @object.email
%p
  姓名：
  = @object.display_name
%p
  权限：
  = @object.roles