config/routes.rb
Rails.application.routes.draw do
  resources :payments

  root 'home#index'
  resources :home
  resources :account_balances

  resources :accounts

  resources :order_payments

  resources :warehouses

  resources :product_histories

  devise_for :employees
  resources :godown_items

  resources :godown_entries do
    member do
      get :do_import
      get :import
      get :check
      get :clear_items
    end
  end

  resources :products

  resources :delivery_items

  resources :deliveries

  resources :partners

  resources :staffs

  resources :companies

  resources :order_items
  resources :product_warehouses

  resources :providers
  resources :employees do
    collection do
      post :add
    end
  end

  resources :orders do
    collection do
      get :prepare_import
      post :import
      get :autocomplete_godown_item_terminal_code
    end
    member do
      get :delivery
      post :add_item
      get :recaculate
      post :pay
    end
  end


end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :partner
  has_many :account_histories

  def add(amount, order, order_payment = nil)
    h = self.account_histories.build
    h.balance_before = self.balance
    h.amount = amount
    self.balance += amount
    h.balance = self.balance
    h.order = order
    h.order_payment = order_payment
    h.save
    self.save
  end
end

app/models/account_history.rb
class AccountHistory < ActiveRecord::Base
  belongs_to :account
  belongs_to :order_payment
  belongs_to :order
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
end

app/models/delivery_item.rb
class DeliveryItem < ActiveRecord::Base
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def admin?
    self.roles && self.roles.include?('admin')
  end
  def to_s
    self.display_name
  end
end

app/models/godown_entry.rb
class GodownEntry < ActiveRecord::Base
  has_many :godown_items
  belongs_to :product
  belongs_to :warehouse
  belongs_to :creator, class_name: 'Employee'
  attr_accessor :import_text
  
  default_scope { order('id desc') }


  after_save :import

  def import
    # 产品名称，终端号，价格, 机身编号
    return true unless self.import_text
    OrderImport.import(self.import_text)
    self.import_text = nil
    true
  end
  def do_import
    OrderImport.all.each do |oi|
      item = self.godown_items.build
      item.terminal_code = oi.terminal_code
      item.sn_code = oi.sn_code
      item.price = oi.price
      if oi.product
        item.product = oi.product
      else
        p = Product.find_or_create_by(name: oi.product_name)
        item.product = p
      end
      item.save
      oi.destroy
    end
  end

  def recaculate
    self.godown_items.each {|item| item.recaculate}
    self.total_items = self.godown_items.count
    self.total_amount = self.godown_items.sum(:amount)
    self.save!
  end

  def valid_for_godown
    self.errors.clear
    if self.status > 0
      self.errors[:base] << "此单已经入库，不能再重复入库。"
      false
    elsif !GodownEntry.where(godown_number: self.godown_number).where('status > 0').empty?
      self.errors[:base] << "Duplicate godown number #{self.godown_number}"
      false
    elsif self.total_items == nil || self.total_items < 1 || self.total_amount == nil || self.total_amount == 0
      self.errors[:base] << 'No godown items'
      false
    else
      true
    end
  end

  def do_godown
    valid_for_godown
    return false unless self.errors.empty?

    self.godown_items.each do |item|
      ProductsWarehouses.add(self.warehouse, item.product, item.items, self)
      item.warehouse = self.warehouse
      item.status = 1
      item.save!
    end
    self.status = 1
    self.save!
  end
end

app/models/godown_item.rb
class GodownItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :warehouse
  belongs_to :godown_entry

  scope :in_stock, -> {where(status: 1)}
  def recaculate
    if self.product
      unless self.price && self.price > 0
        self.price = self.product.godown_price
      end
      self.items = 1 unless self.items && self.items > 0
      self.price = 0 unless self.price
      self.amount = self.items * self.price
      self.save
    end
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items, dependent: :destroy
  has_many :order_payments, dependent: :destroy

  belongs_to :partner
  default_scope { order('id desc')}

  attr_accessor :foo

  def valid_for_order
    return false unless (self.status == 0) && self.partner && (self.total_items > 0) && (self.order_items.count > 0)
    true
  end
  def valid_for_pay
    return false unless (self.status == 1 || self.status == 2)
    true
  end
  def recaculate
    return false unless self.status == 0
    self.order_items.each { |item| item.recaculate }
    self.total_items = self.order_items.count
    self.total_amount = self.order_items.sum(:amount)
    self.save
  end
  def pay(amount, notes = nil)
    return false unless valid_for_pay
    p = self.order_payments.build
    p.balance_before = self.balance
    p.pay_amount = amount
    p.notes = notes
    self.balance = p.balance = p.balance_before - amount
    p.save
    self.partner.account.add(-amount, self, p) if self.partner && self.partner.account
    self.status = 2 if self.status = 1
    self.status = 3 if self.balance == 0
    self.save
  end
  def self.import(import_text)
    # 订单号，日期，串码，合作伙伴，备注
    import_text.split(/\n/).each do |line|
      cs = line.split(/[\t]/)
      if cs.length > 3
        order_number = cs[0]
        order_number = DateTime.now.to_id unless cs[0]

        order = Order.find_or_create_by(order_number: order_number)
        order.order_date = cs[1].to_date
        if cs[3] && !cs[3].blank?
          order.partner = Partner.find_or_create_by(partner_name: cs[3])
        end
        item = order.order_items.build
        item.t_code = cs[2]
        item.notes = cs[4] if cs.length > 4
        order.save
      end
    end
    true
  end
end

app/models/order_import.rb
class OrderImport < ActiveRecord::Base
  belongs_to :product
  def self.import(import_text)
    # 产品名称， 终端编号，价格, 机身编号 
    import_text.split(/\n/).each do |line|
      cs = line.split(/[\t]/)
      if cs.length > 2
        oi = OrderImport.new(product_name: cs[0], terminal_code: cs[1], price: cs[2], status: 0)
        oi.sn_code = cs[3] if cs.length > 3
        oi.product = Product.find_by_name(oi.product_name) if oi.product_name
        oi.save
      end
    end
    true
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :godown_item

  def recaculate
    unless self.godown_item
      if self.t_code
        self.godown_item = GodownItem.find_by_terminal_code(self.t_code)
      end
    end
    if self.godown_item && self.godown_item.product
      price = self.godown_item.product.sale_price

      self.product = self.godown_item.product
      self.price = price unless self.price && self.price > 0.0
      self.items = 1 unless self.items
      self.amount = self.price * self.items
      self.save
    end
    true
  end

  def delivery
    return false unless self.status == 0 && self.godown_item && self.godown_item.status == 1
    recaculate
    item.status = 1
    item.save
    item.godown_item.status = 2
    item.godown_item.save


  end

end

app/models/order_payment.rb
class OrderPayment < ActiveRecord::Base
  
end

app/models/partner.rb
class Partner < ActiveRecord::Base
  has_one :account
  def to_s
    "#{self.partner_name}(#{self.contact} #{self.tel})"
  end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :order
  belongs_to :partner
  belongs_to :account
end

app/models/prepare_data.rb
class PrepareData < ActiveRecord::Base
  def self.import(import_text, usage)
    import_text.split(/\n/).each do |line|
      row = self.new(usage: usage, status: 0)
      line.split(/[\t]/).each_with_index do |dt, idx|
        row["c#{idx}"] = dt if dt && !dt.blank?
      end
      row.save
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :warehouses
end

app/models/product_history.rb
class ProductHistory < ActiveRecord::Base
  belongs_to :operate_sheet, polymorphic: true
  belongs_to :warehouse
  belongs_to :product
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  has_many :orders
end

app/models/staff.rb
class Staff < ActiveRecord::Base
end

app/models/warehouse.rb
class Warehouse < ActiveRecord::Base
  has_and_belongs_to_many :products

end

app/views/shared/_main_menu.html.haml
%nav.navbar.navbar-default{:role => "navigation"}
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"}
        = image_tag(("wooul-logo.png"), :alt => "POS进出库管理系统")
        POS库存管理
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.active
          = link_to '入库', godown_entries_path
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            库存
            %b.caret
          %ul.dropdown-menu
            %li
              = link_to '各仓库库存', warehouses_path
            %li
              = link_to '序列号清单', godown_items_path
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            出库
            %b.caret
          %ul.dropdown-menu
            %li
              = link_to '出库单', orders_path
            %li
              = link_to '未付款客户', accounts_path
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            数据
            %b.caret
          %ul.dropdown-menu
            %li
              = link_to '产品', products_path
            %li
              = link_to '仓库', warehouses_path
            %li
              = link_to '合作伙伴', partners_path
            %li
              %a{:href => "#"} Something else here
            %li.divider
            %li
              %a{:href => "#"} Separated link
            - if current_employee && current_employee.admin?
              %li.divider
              %li= link_to '员工', employees_path

      %ul.nav.navbar-nav.navbar-right
        - if current_employee
          %li
            = link_to  "欢迎 #{current_employee.display_name}! #{current_employee.admin? ? '[admin]' : ''}", employee_path(current_employee)
          %li= link_to '退出登录', destroy_employee_session_path, method: 'delete'
        - else
          %li 
            %span.pleaselogin 请登录！
    / /.nav-collapse