config/routes.rb
Rails.application.routes.draw do
  resources :payments

  root 'home#index'
  resources :home
  resources :account_balances

  resources :accounts

  resources :order_payments

  resources :warehouses

  resources :product_histories

  devise_for :employees
  resources :godown_items

  resources :godown_entries do
    member do
      get :do_import
      get :import
      get :check
      get :clear_items
    end
  end

  resources :products

  resources :delivery_items

  resources :deliveries

  resources :partners

  resources :staffs

  resources :companies

  resources :order_items
  resources :product_warehouses

  resources :providers
  resources :employees do
    collection do
      post :add
    end
  end

  resources :orders do
    collection do
      get :prepare_import
      post :import
      get :autocomplete_godown_item_terminal_code
    end
    member do
      get :delivery
      post :add_item
      get :recaculate
      post :pay
    end
  end


end

app/models/godown_entry.rb
class GodownEntry < ActiveRecord::Base
  has_many :godown_items
  belongs_to :product
  belongs_to :warehouse
  belongs_to :creator, class_name: 'Employee'
  attr_accessor :import_text
  
  default_scope { order('id desc') }


  after_save :import

  def import
    # 产品名称，终端号，价格, 机身编号
    return true unless self.import_text
    OrderImport.import(self.import_text)
    self.import_text = nil
    true
  end
  def do_import
    OrderImport.all.each do |oi|
      item = self.godown_items.build
      item.terminal_code = oi.terminal_code
      item.sn_code = oi.sn_code
      item.price = oi.price
      if oi.product
        item.product = oi.product
      else
        p = Product.find_or_create_by(name: oi.product_name)
        item.product = p
      end
      item.save
      oi.destroy
    end
  end

  def recaculate
    self.godown_items.each {|item| item.recaculate}
    self.total_items = self.godown_items.count
    self.total_amount = self.godown_items.sum(:amount)
    self.save!
  end

  def valid_for_godown
    self.errors.clear
    if self.status > 0
      self.errors[:base] << "此单已经入库，不能再重复入库。"
      false
    elsif !GodownEntry.where(godown_number: self.godown_number).where('status > 0').empty?
      self.errors[:base] << "Duplicate godown number #{self.godown_number}"
      false
    elsif self.total_items == nil || self.total_items < 1 || self.total_amount == nil || self.total_amount == 0
      self.errors[:base] << 'No godown items'
      false
    else
      true
    end
  end

  def do_godown
    valid_for_godown
    return false unless self.errors.empty?

    self.godown_items.each do |item|
      ProductsWarehouses.add(self.warehouse, item.product, item.items, self)
      item.warehouse = self.warehouse
      item.status = 1
      item.save!
    end
    self.status = 1
    self.save!
  end
end

app/controllers/godown_entries_controller.rb
class GodownEntriesController < ResourcesController
  def check
    load_object
    @object.recaculate
    unless @object.valid_for_godown
      flash[:error] = @object.errors.full_messages.to_sentence

    end
    redirect_to @object
  end

  def import
    load_object
    unless @object.do_import
      flash[:error] = @object.errors.full_messages.to_sentence
    end
    render :show
  end

  def do_import
    load_object
    @object.recaculate
    unless @object.do_godown
      flash[:error] = @object.errors.full_messages.to_sentence
    end
    redirect_to @object
  end

  def clear_items
    load_object
    OrderImport.destroy_all
    redirect_to action: :edit
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def godown_entry_params
      params.require(:godown_entry).permit(:godown_number, :product_id, :total_items, :total_amount, :status, :creator_id)
    end
end

app/views/godown_entries/_form.html.haml
= simple_form_for(@object) do |f|
  = f.error_notification

  .form-inputs
    .row
      .col-md-6
        = f.input :godown_number
      .col-md-6
        = f.association :warehouse

    = f.input :import_text, as: :text

  .form-actions
    = f.button :submit, '保存'

- t_items = 0
- t_amount = 0.0

%p 待导入数据：
%table.table.table-bordered.table-striped.table-hover
  %thead
    %tr
      %th 产品名称
      %th 已有产品
      %th 终端编号
      %th 价格
  %tbody
    - OrderImport.all.each do |imp|
      - t_items += 1
      - t_amount += imp.price
      %tr
        %td= imp.product_name
        %td= "#{imp.product.name}(#{imp.product.id})" if imp.product
        %td= imp.terminal_code
        %td= imp.price
  %tfoot
    %tr
      %td
      %td 合计
      %td= t_items
      %td= t_amount

app/views/godown_entries/_items.html.haml
%table.table.table-bordered.table-striped.table-hover
  %thead
    %tr
      %th 型号
      %th 终端号
      %th 机身编号
      %th 价格
      %th 数量
      %th 金额
      %th 状态
  %tbody
    - @object.godown_items.each do |godown_item|
      %tr
        %td= godown_item.product.name if godown_item.product
        %td= best_in_place godown_item, :terminal_code, type: :input
        %td= best_in_place godown_item, :sn_code, type: :input
        %td= best_in_place godown_item, :price, type: :input
        %td= best_in_place godown_item, :items, type: :input
        %td= godown_item.amount
        %td= status_text(godown_item)
  %tfoot
    %tr
      %td{colspan: 4} 合计：
      %td= @object.total_items
      %td= @object.total_amount
      %td= status_text(@object)
    %tr
      %td{colspan: 4} &nbsp;
      %td{colspan: 3}
        制单人：
        = @object.creator.display_name if @object.creator

app/views/godown_entries/edit.html.haml
.toolbox
  = link_to '列表', godown_entries_path
  |
  = link_to '返回入库单', @object
  |
  = link_to '确认导入', import_godown_entry_path(@object)

= render 'form'
= toolbox_button '清空待导入输入', clear_items_godown_entry_path(@object), data: {confirm: '确认清空待导入数据吗？'}
= render 'items'

app/views/godown_entries/index.html.haml
.toolbox
  = toolbox_button '新增入库单', new_godown_entry_path

= will_paginate @collection
%table.table.table-bordered.table-striped.table-hover
  %tr
    %th 入库单号
    %th 数量
    %th 金额
    %th 状态
    %th 操作人
    %th 备注
    %th

  - @collection.each do |godown_entry|
    %tr
      %td= godown_entry.godown_number
      %td.num= godown_entry.total_items
      %td.num= number_with_delimiter godown_entry.total_amount
      %td= status_text(godown_entry)
      %td= godown_entry.creator
      %td= godown_entry.notes
      %td
        = link_to '详情', godown_entry
        |
        = link_to '修改', edit_godown_entry_path(godown_entry)
        |
        = link_to '删除', godown_entry, :method => :delete, :data => { :confirm => '确定删除吗？' }

= will_paginate @collection

app/views/godown_entries/new.html.haml
.toolbox= link_to '返回列表', godown_entries_path

%h2 新建入库单

= render 'form'

app/views/godown_entries/show.html.haml
%p
  %b 单号:
  = @object.godown_number
  %b 仓库：
  = @object.warehouse.name if @object.warehouse

.toolbox
  = link_to '列表', godown_entries_path
  |
  = link_to '修改', edit_godown_entry_path(@object)
  |
  = link_to '检查', check_godown_entry_path(@object)
  |
  = link_to '入库', do_import_godown_entry_path(@object)

= render partial: 'items'